import metadata from "../../public/examples/metadata.json";

/** Generated by scripts/build-example.ts from a reviewed, locally rendered fixture. */
export const DEMO_EXAMPLE = {
  placeId: metadata.placeId,
  mode: "fixture" as const,
  purpose: "youth_story" as const,
  reviewedAt: metadata.reviewedAt,
  title: metadata.title,
  description: metadata.description,
  images: metadata.cards.map(card => card.image),
  metadataUrl: "/examples/metadata.json",
  sourceManifestUrl: "/examples/sources.json",
  reviewManifestUrl: "/examples/review.json",
};
